language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
      virtualenv:
          system_site_packages: true
      env:
        - R2_VERSION=2.9.0 R2M2_UBUNTU=yes

    - os: linux
      dist: trusty
      python: 2.7
      sudo: required
      env:
        - R2M2_DOCKER=yes

    - os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - R2_VERSION=3.4.0 R2M2_OSX=yes

before_install:
  - if [ ! -z $R2M2_DOCKER ]; then docker build -t travis/r2m2 . ; fi

install:
  ### Ubuntu & OS X ###
  # Install C related dependencies
  - if [ ! -z $R2M2_UBUNTU ]; then sudo apt-get install make gcc git pkg-config; fi
  # Install Python related dependencies
  - if [ ! -z $R2M2_UBUNTU ]; then sudo apt-get install libffi-dev libpython-dev; fi
  - if [ -z $R2M2_DOCKER ]; then pip2 install cffi jinja2; fi
  # Install radare2
  - if [ -z $R2M2_DOCKER ]; then git clone https://github.com/radare/radare2 --depth 1 --branch $R2_VERSION; cd radare2; ./configure; cd shlr; make capstone-sync; cd ..; ./sys/user.sh --without-pull; cd ..; fi
  - if [ -z $R2M2_DOCKER ]; then export PATH=$HOME/bin/:$PATH; fi
  - if [ -z $R2M2_DOCKER ]; then export PKG_CONFIG_PATH=~/bin/prefix/radare2/lib/pkgconfig/; fi
  # Install miasm2
  - if [ -z $R2M2_DOCKER ]; then pip2 install pyparsing future; fi
  - if [ -z $R2M2_DOCKER ]; then git clone https://github.com/cea-sec/miasm --depth 1; fi
  # Install bats
  - if [ -z $R2M2_DOCKER ]; then git clone https://github.com/sstephenson/bats --depth 1; fi
  - if [ -z $R2M2_DOCKER ]; then export PATH=bats/bin:$PATH; fi

script:
  - env
  ### Ubuntu & OS X ###
  # Build & install r2m2
  - if [ -z $R2M2_DOCKER ]; then make install; fi
  - if [ -z $R2M2_DOCKER ]; then export PYTHONPATH=miasm/; fi
  # Launch tests
  - if [ -z $R2M2_DOCKER ]; then bats test/r2m2.bats; fi
  ### Docker ###
  # Launch Docker based tests
  - if [ ! -z $R2M2_DOCKER ]; then docker run --rm -it travis/r2m2 bats test/r2m2.bats; fi
